### ISSUE TITLE
UnicodeDecodeError 

### ISSUE THREAD

**Issue by Jean332** [zjuela/LapSRN-tensorflow#2]
Sorry,when I run the code,I got a UnicodeDecodeError 
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
D:\Anaconda\lib\site-packages\numpy\lib\format.py in read_array(fp, allow_pickle, pickle_kwargs)
    639         try:
--> 640             array = pickle.load(fp, **pickle_kwargs)
    641         except UnicodeError as err:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 0: ordinal not in range(128)

During handling of the above exception, another exception occurred:

UnicodeError                              Traceback (most recent call last)
E:\jupyterNote\图像分辨率\LapSRN-tensorflow-master\main.py in <module>()
    210     tl.global_flag['mode'] = args.mode
    211     if tl.global_flag['mode'] == 'train':
--> 212         train()
    213     elif tl.global_flag['mode'] == 'test':
    214         if (args.file is None):

E:\jupyterNote\图像分辨率\LapSRN-tensorflow-master\main.py in train()
    121     sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=False))
    122     tl.layers.initialize_global_variables(sess)
--> 123     tl.files.load_and_assign_npz(sess=sess, name=checkpoint_dir+'/params_{}.npz'.format(tl.global_flag['mode']), network=net_image2)
    124 
    125     ###========================== PRE-LOAD DATA ===========================###

E:\jupyterNote\图像分辨率\LapSRN-tensorflow-master\tensorlayer\files.py in load_and_assign_npz(sess, name, network)
    720         return False
    721     else:
--> 722         params = load_npz(name=name)
    723         assign_params(sess, params, network)
    724         print("[*] Load {} SUCCESS!".format(name))

E:\jupyterNote\图像分辨率\LapSRN-tensorflow-master\tensorlayer\files.py in load_npz(path, name)
    632     #     params = val
    633     #     return params
--> 634     return d['params']
    635     # print(d.items()[0][1]['params'])
    636     # exit()

D:\Anaconda\lib\site-packages\numpy\lib\npyio.py in __getitem__(self, key)
    231                 return format.read_array(bytes,
    232                                          allow_pickle=self.allow_pickle,
--> 233                                          pickle_kwargs=self.pickle_kwargs)
    234             else:
    235                 return self.zip.read(key)

D:\Anaconda\lib\site-packages\numpy\lib\format.py in read_array(fp, allow_pickle, pickle_kwargs)
    644                 raise UnicodeError("Unpickling a python object failed: %r\n"
    645                                    "You may need to pass the encoding= option "
--> 646                                    "to numpy.load" % (err,))
    647             raise
    648     else:

UnicodeError: Unpickling a python object failed: UnicodeDecodeError('ascii', b'\xe1……
I don't know how to deal with it……

**Comment by godardt** [comment]
Same issue here

**Comment by zjuela** [comment]
@Jean332 do you use python3 or python2? The error seems to relate to python3. 
If you are using python3, please try python2 to see if it works.

**Comment by whulc** [comment]
Have you solver this problem? I meet the same one.

**Comment by zjuela** [comment]
@whulc check https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte to see if it helps

**Comment by whulc** [comment]
https://stackoverflow.com/questions/24105148/load-python-2-npy-file-in-python-3, I get through it in this way.

**Comment by UrYuWang** [comment]
It doesn't work though.
