### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 0: ordinal not in range(128)?

### ISSUE THREAD

**Issue by dcdethan** [zjuela/LapSRN-tensorflow#6]
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0)
Traceback (most recent call last):
  File "/home/stephen/tf_3.6/lib/python3.6/site-packages/numpy/lib/format.py", line 640, in read_array
    array = pickle.load(fp, **pickle_kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 0: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 212, in <module>
    train()
  File "main.py", line 123, in train
    tl.files.load_and_assign_npz(sess=sess, name=checkpoint_dir+'/params_{}.npz'.format(tl.global_flag['mode']), network=net_image2)
  File "/home/stephen/test/LapSRN-tensorflow/tensorlayer/files.py", line 722, in load_and_assign_npz
    params = load_npz(name=name)
  File "/home/stephen/test/LapSRN-tensorflow/tensorlayer/files.py", line 634, in load_npz
    return d['params']
  File "/home/stephen/tf_3.6/lib/python3.6/site-packages/numpy/lib/npyio.py", line 233, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/home/stephen/tf_3.6/lib/python3.6/site-packages/numpy/lib/format.py", line 646, in read_array
    "to numpy.load" % (err,))
UnicodeError: Unpickling a python object failed: UnicodeDecodeError('ascii', b'\xe1\x1e\x99=%!U\xbd(}%=\xc0\x15R\xbdp\xb8\xb2\xbd\xc4I\xa3\xbc8\x87\x99\xbd\xf4\xd1t=k\x04Q;a\x8f\x06\xbd\xc5\xbc\xbf=\x1b\x8e\x8f\xbd\x08\xb1\'\xbb8\xbf=\xbd\x95=W=$I\x80;\xd1\x8f\x9f=\xd5\'\xe6\xbc|Si\xbc?\x8b\xc1\xbc\x008\xfb=}\x85\xf5<\xf5\x0b:\xbc\xc4\xbe\x91\xbc\xb5\xf1\x81\xbd\xe3\xdc%\xbd75\x9a\xbbu\xdaM=?
...........................
......................
/\x98:\xbdL\xb11=\x88\xb9\xb9\xbd\x05\xa2t\xbdkF\xa7=\x03\xf2\xc9<\x02 \xc2\xbd\xf8\x88\x87\xbd\xc6>\xf0=j,\r\xbe\xa3\'\xcc\xbcA\x88B;r\x83\x8a\xbc_\x86\xc6\xbc\x94\xcd\xa7<\xd1\x06N=\x10\x05\xc5=\x80R\xac=f\x89\x10\xbc\xf0NF\xbdFi\x1f=\x0f\x17t\xbck\xd9\xfd;+f\xb8=\x07\x16O=)\xcd\xbb=\xf1^0=\x08w}\xbd\xf6\x19\x83\xbd\x8d\xf4\xc7\xbc\x85ax\xbd\xad\xf1\xbc;W\x9d\x1f<\xdc\xdd\xe2<%\xb8L\xbc\xd1\x0f\x82;\x94!\x00\xbc\\\xb2\x9d<\'\x13\x8b;-\xcb\x98<\x8c\x10\xae<\xa4\xf4_<8\n\xe3\xbcE\x1e6=\xbe\xee\xe7\xbc\xda\xf3\xcc=^\xe0\x9e\xbc\xfe\xb5j<\x8du\x9a\xbc\xe0\xf7\xec<8\xa1\'\xbd&g\xff\xbc!-\x8b=\x93\x8d\xe6\xbbzL\xbc\xbc\xb2D\x9a<t\xbel\xbd\xc0\x11F9\r\xd6\x86\xbc', 0, 1, 'ordinal not in range(128)')
You may need to pass the encoding= option to numpy.load

How should I do?

**Comment by zjuela** [comment]
It is a duplicate issue, 
check https://github.com/zjuela/LapSRN-tensorflow/issues/2

**Comment by dcdethan** [comment]
thanks!
